# Site settings
title: "Jonathan Pichot"
description: "Passionate urbanist, skeptical technologist"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jonathan Pichot"
resume_title:                   "Passionate urbanist, skeptical technologist"
resume_contact_email:           "jonathan@pichot.us"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/_pichot"
  resume_linkedin_url:          "https://www.linkedin.com/in/jonathanpichot"
  resume_medium_url:            "https://medium.com/@pichot"

# Design settings
resume_theme:                   default
